### ISSUE TITLE
how to run on large cohort

### ISSUE THREAD

**Issue by brentp** [Illumina/paragraph#17]
The example has effectively this:
```
python3 bin/multigrmpy.py -i $sites_vcf \
                          -m $manifest \
                          -r $reference_fasta \
                          -o $out_dir
```
if $manifest has hundreds of samples, can I genotype each sample seperately--i.e. will paragraph give different results if I split by sample (but the sites_vcf is the same?)

or should parallelization only be by site?
also, what does `paragraph` do with BND elements?

**Comment by iqbal-lab** [comment]
What is BND?

**Comment by brentp** [comment]
It's a "Break-end" -- something that can't be classified as a DEL/DUP/etc. See the VCF spec for the full gory details. I just want to know if it will ignore those or if I must remove them from the VCF.

**Comment by traxexx** [comment]
You can genotype each sample separately. Or you can split the VCF into chunks and feed them into Paragraph separately. Results won't be different.

BND is not supported in v2.2. They need to be removed from the input VCF.

It is hard to decide what kind of variant a BND is. Instead of providing unconfident information, we prefer not supporting it for now.
