### ISSUE TITLE
How to better call and genotype population SVs?

### ISSUE THREAD

**Issue by biozzq** [Illumina/paragraph#52]
Hi @traxexx @KamilSJaron 

Thanks for your contribution. I found the python script (convertManta2Paragraph_compatible_vcf.py) you uploaded ommitted the INSs whose INFO fields contain RIGHT_SVINSSEQ and LEFT_SVINSSEQ. Maybe paragraph can not genotype these variants so you ommitted them. Although the short reads mapping can not give us enough information about the complete inserted sequences, I have checked some insertions in IGV and found some with above two INFO fileds are actually make sense.

To @traxexx 
It's difficult to assemble the complete inserted sequences (based on mapping to reference genome) when the INSs are longer than the read lengths. Thus, Manta reported the RIGHT_SVINSSEQ and LEFT_SVINSSEQ in these INSs. I wonder whether paragraph can handle these SVs properly.

Moreover, I found that the deviations of breakpoint, maybe over 100bp or even large as I used SURVIVOR to merge all individual VCFs into one population VCF using a maximum allowed distance of 1kb measured pairwise between breakpoints (begin1 vs begin2, end1 vs end2), affect the genotype results greatly. Do you have any suggestions about the discovery of population SVs before genotyping?

Sincerely,
Zheng Zhuqing

**Comment by KamilSJaron** [comment]
Hello Zheng Zhuqing,

the incomplete insertions (those that have RIGHT_SVINSSEQ/LEFT_SVINSSEQ) are genotypeable in principle, but it's currently not implemented in Paragaph therefore they are ommited.

Survivor is not a good tool for unifying SV calls before genotyping because it's not trying to resove the consensus sequences which are necessary for genotyping. Also, it's quite nuts when you think about that. survivor lumps together 50 bases long SVs that are < than some crazy number of bases apart from each other. I ended up cross genotyping on the whole population and taking consensus. 

I also recommend not to trust callers, you can curate your SV dataset using tools like https://github.com/ryanlayer/samplot. It was really a huge help for my study.

Good luck

**Comment by biozzq** [comment]
Dear @KamilSJaron 

Thank you. Sorry, I can not fully understand the workflow you used. Do you mean that you first discover high quality SVs in one sample, and then genotype them on the whole population? For example, if you have 100 samples, you will get 100 VCF files which all contain the genotype information for all the 100 samples. Then, you will take consensus (which tool did you use to finish this process). In my mind, above process can ensure the accuracy of the breakpoints for each sample when genotyping.

That's a good tool for us to visual the variants, I will have a try.

Sincerely,
Zheng Zhuqing

**Comment by KamilSJaron** [comment]
Yes, that's exactly right - I genotyped variants called in all individuals (i.e. number of genotyping runs will be the number of individuals squared), but I had just 6 samples per population. For example, If I had two close or overlapping variants A and B called in samples 1 and 2 respectively, I merged them into one only if both A/B was called in both individuals 1/2. That was my idea and I was writing my own scripts to manipulate the data. Obviously, this approach is not suitable for bigger sample sizes.

**Comment by traxexx** [comment]
@biozzq Paragraph only use reads that span the breakpoints. It is possible to incorporate those partially assembled SVs as long as:
inserted sequences from both end exist
 and
these sequences are longer than read lengths.
I can try to come up with a python script if you need...
